### ISSUE TITLE
[Issue] some issues that from a group member

### ISSUE THREAD

**Issue by CoolLKKPS** [d-rafferty/lethal-tube-removal#35] opened 2024-05-07 09:23 UTC
this issue is from a group member, and i forward to here

**Comment by CoolLKKPS** [comment] 2024-05-07 09:23
1. if u turn off the ship speaker, after team did not meet the profit quota, speaker won't work and the ship door won't open, and the game cannot continue

**Comment by CoolLKKPS** [comment] 2024-05-07 09:33
2. with door tubes removed, u won't be able to load into the game, we already troubleshoot some conflict, still happen with LLL disabled

update: with vanilla this issue won't happen, so this is a conflict issue

**Comment by d-rafferty** [comment] 2024-05-07 15:42
Interesting. The speaker bug is something we dealt with in the past, I did recently make some changes to speakers so it might be the culprit.

As far as the door tubes that is strange.

What version number of LethalPipeRemoval was this on?

**Comment by d-rafferty** [comment] 2024-05-07 16:10
I have recreated the speaker bug, I have an idea for a potential workaround for this and I'll work on that soon.

As far as the door tubes bug, any conflict with LLL should have been resolved with  v1.6.6 which came out yesterday. I was unable to recreate this. So if you're not on that version, updating should solve it. 

If the issue is not LLL, and a different mod you have installed, I'll have to know which mod it is to be able to find a fix.

**Comment by CoolLKKPS** [comment] 2024-05-08 04:10
@d-rafferty sure, conflict with LethalPosters made by femboytv

**Comment by CoolLKKPS** [comment] 2024-05-08 04:53
uh btw can u do me a favor, can u help me send those feedback to his discord?:
[Rosies_Moons](https://thunderstore.io/c/lethal-company/p/RosiePies/Rosies_Moons) are now conflict with many more mods, for me this conflict with HDLethalCompany (only when in summit moon, one of my favorite moon bc i like snow) and minor conflict with Oxygen (will count to breakable when in dungeon)

**Comment by 1410677474** [comment] 2024-05-09 16:38
conflict with LethalPosters made by femboytv，When removing posters

**Comment by 1410677474** [comment] 2024-05-09 16:52
> I have recreated the speaker bug, I have an idea for a potential workaround for this and I'll work on that soon.
> 
> As far as the door tubes bug, any conflict with LLL should have been resolved with v1.6.6 which came out yesterday. I was unable to recreate this. So if you're not on that version, updating should solve it.
> 
> If the issue is not LLL, and a different mod you have installed, I'll have to know which mod it is to be able to find a fix.

If Automatic Terminal Reposition is enabled, Terminal Reposition will be recover as before when you are fired

**Comment by d-rafferty** [comment] 2024-05-12 00:10
I've made a note of the conflict and the Terminal Reposition errors, will look into them.

But for now the firing soft-lock should no longer occur. #38 

Will be live with v1.6.7

**Comment by d-rafferty** [comment] 2024-05-12 00:29
Terminal reposition fixed #39 
Also in v1.6.7

As far as the posters conflict, I am aware of it, and will look into it further in the future. However I am unsure there is much I can do to resolve this issue here. I will close this issue for now but if I ever find a reason for that conflict I can fix, I will be sure to update you in this thread.

**Closed as completed by d-rafferty** 2024-05-12 00:29 UTC
Labels: bug
